import React, { useState, useEffect } from 'react'
import { Search, TrendingUp, Download, AlertTriangle, CheckCircle, Pill, ChevronRight } from 'lucide-react'
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Legend } from 'recharts'
import { top100Drugs } from '../data/drugs'

function PharmaSearch() {
  const [query, setQuery] = useState('')
  const [selectedDrug, setSelectedDrug] = useState(null)
  const [overpayment, setOverpayment] = useState(0)
  const [report, setReport] = useState(null)
  const [generatingReport, setGeneratingReport] = useState(false)

  const results = query.length >= 2
    ? top100Drugs.filter(
        (d) =>
          d.brandName.toLowerCase().includes(query.toLowerCase()) ||
          d.activeIngredient.toLowerCase().includes(query.toLowerCase())
      )
    : []

  useEffect(() => {
    if (!selectedDrug) { setOverpayment(0); return }
    const yearlyOverpay = (selectedDrug.brandPriceAUD - selectedDrug.genericPriceAUD) * 12
    let current = 0
    const step = yearlyOverpay / 60
    const timer = setInterval(() => {
      current += step
      if (current >= yearlyOverpay) { setOverpayment(yearlyOverpay); clearInterval(timer) }
      else { setOverpayment(current) }
    }, 1000 / 60)
    return () => clearInterval(timer)
  }, [selectedDrug])

  const handleGenerateReport = () => {
    if (!selectedDrug) return
    setGeneratingReport(true)
    
    const drug = selectedDrug
    const savings = (drug.brandPriceAUD - drug.genericPriceAUD) * 12
    
    setTimeout(() => {
      const reportContent = `FULL TRANSPARENCY REPORT
${'='.repeat(50)}

MEDICATION: ${drug.brandName}
ACTIVE INGREDIENT: ${drug.activeIngredient}
ARTG NUMBER: ${drug.artgNumber}
PBS CODE: ${drug.pbsCode}
CATEGORY: ${drug.category}
BIO-EQUIVALENT: ${drug.bioEquivalent ? 'Confirmed' : 'Not Confirmed'}

${'-'.repeat(50)}

PRICE GAP ANALYSIS

Brand Price (Australia):    $${drug.brandPriceAUD.toFixed(2)} AUD
Generic Price (Australia):  $${drug.genericPriceAUD.toFixed(2)} AUD
Global Manufacturer Price:  $${drug.globalMfrPriceAUD.toFixed(2)} AUD

Annual Savings with Generic: $${savings.toFixed(2)} AUD
Savings Percentage: ${((1 - drug.genericPriceAUD / drug.brandPriceAUD) * 100).toFixed(0)}%

${'-'.repeat(50)}

PHARMACIST SUBSTITUTION SCRIPT

"Hi, I have a prescription for ${drug.brandName}. I understand that ${drug.activeIngredient} is the generic equivalent and is bio-equivalent. Can you please substitute the generic version today?"

${'-'.repeat(50)}

GP CONSULTATION GUIDE

1. Ask your GP: "Can you prescribe ${drug.activeIngredient} instead of ${drug.brandName}?"
2. Under the PBS, you have the right to request generic substitution.
3. Your GP can write "No Substitution" on the prescription, but you can request they remove this.
4. Generic medications must meet the same TGA standards as brand-name medications.

${'-'.repeat(50)}

OFFICIAL REFERENCES

- PBS Search: https://www.pbs.gov.au/
- ARTG Search: https://www.tga.gov.au/resources/artg
- TGA Generic Substitution: https://www.tga.gov.au/news/safety-information/generic-medicines

${'-'.repeat(50)}

DISCLAIMER: This report was generated by Apex Global Shield using publicly available data from pbs.gov.au, tga.gov.au, and legislation.gov.au. It may contain errors, inaccuracies, or outdated information. This is an information and research tool, NOT medical or pharmaceutical advice. Verify all information independently and consult a qualified healthcare professional before making medication decisions.`

      setReport(reportContent)
      setGeneratingReport(false)
    }, 2000)
  }

  const chartData = selectedDrug ? [
    { name: 'Brand (AU)', price: selectedDrug.brandPriceAUD },
    { name: 'Generic (AU)', price: selectedDrug.genericPriceAUD },
    { name: 'Global Mfr', price: selectedDrug.globalMfrPriceAUD }
  ] : []

  return (
    <div className="max-w-4xl mx-auto px-4 py-12">
      {/* Header */}
      <div className="text-center mb-12">
        <div className="inline-flex items-center gap-2 bg-gold/10 border border-gold/20 rounded-full px-4 py-2 mb-6">
          <Pill className="w-4 h-4 text-gold" />
          <span className="text-gold text-xs tracking-widest font-heading">SHIELD 02</span>
        </div>
        <h1 className="font-heading text-3xl md:text-4xl font-bold text-foreground mb-4">
          THERAPEUTIC TRANSPARENCY PORTAL
        </h1>
        <p className="text-muted-foreground text-lg max-w-2xl mx-auto">
          Search any brand-name medication to uncover its generic equivalent, ARTG listing, and the true global manufacturer cost. Knowledge is your right.
          <span className="text-gold font-bold"> Completely free. Always.</span>
        </p>
      </div>

      {/* Search Section */}
      <div className="card mb-8">
        <div className="relative">
          <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-muted-foreground" />
          <input
            type="text"
            className="input w-full pl-12"
            placeholder="Enter brand name (e.g. Lipitor, Nexium, Ventolin)..."
            value={query}
            onChange={(e) => { setQuery(e.target.value); setSelectedDrug(null); setReport(null) }}
          />
        </div>
        {results.length > 0 && !selectedDrug && (
          <div className="mt-4 border border-border rounded-sm divide-y divide-border">
            {results.map((drug, i) => (
              <button
                key={i}
                onClick={() => { setSelectedDrug(drug); setQuery(drug.brandName) }}
                className="w-full text-left px-5 py-4 hover:bg-card-elevated transition-colors flex items-center justify-between"
              >
                <div>
                  <span className="text-foreground font-bold">{drug.brandName}</span>
                  <span className="text-muted-foreground text-sm ml-2">{drug.category}</span>
                </div>
                <span className="text-muted-foreground text-sm">{drug.activeIngredient}</span>
              </button>
            ))}
          </div>
        )}
      </div>

      {/* Results */}
      {selectedDrug && (
        <div className="space-y-8">
          {/* Overpayment Counter */}
          <div className="card border-gold/30 text-center">
            <div className="flex items-center justify-center gap-2 mb-2">
              <TrendingUp className="w-5 h-5 text-destructive" />
              <span className="font-heading text-sm tracking-widest text-gold">ESTIMATED ANNUAL OVERPAYMENT</span>
            </div>
            <div className="font-heading text-4xl md:text-5xl font-bold text-destructive mb-2">
              ${overpayment.toFixed(2)}
            </div>
            <p className="text-muted-foreground text-sm">
              vs generic equivalent ({selectedDrug.activeIngredient})
            </p>
          </div>

          {/* Drug Details */}
          <div className="card">
            <div className="flex items-start gap-4 mb-6">
              <div className="w-12 h-12 bg-gold/10 rounded-sm flex items-center justify-center">
                <Pill className="w-6 h-6 text-gold" />
              </div>
              <div>
                <h3 className="font-heading text-xl font-bold text-foreground">{selectedDrug.brandName}</h3>
                <p className="text-muted-foreground text-sm">{selectedDrug.artgNumber} · {selectedDrug.description}</p>
                <div className="flex items-center gap-4 mt-2">
                  <span className="text-muted-foreground text-sm">Active Ingredient: {selectedDrug.activeIngredient}</span>
                  <span className="text-muted-foreground text-sm">Bio-Equivalent: {selectedDrug.bioEquivalent ? 'Confirmed' : 'Not Confirmed'}</span>
                </div>
              </div>
            </div>

            {/* Price Gap Chart */}
            <div className="mb-6">
              <h4 className="font-heading text-sm tracking-widest text-gold mb-4">PRICE GAP ANALYSIS</h4>
              <ResponsiveContainer width="100%" height={250}>
                <BarChart data={chartData}>
                  <CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" />
                  <XAxis dataKey="name" stroke="hsl(var(--muted-foreground))" fontSize={12} />
                  <YAxis stroke="hsl(var(--muted-foreground))" fontSize={12} />
                  <Tooltip contentStyle={{ backgroundColor: 'hsl(var(--card))', border: '1px solid hsl(var(--border))' }} />
                  <Legend />
                  <Bar dataKey="price" fill="hsl(var(--gold))" name="Price (AUD)" />
                </BarChart>
              </ResponsiveContainer>
            </div>
          </div>

          {/* Full Report */}
          <div className="card">
            <h3 className="font-heading text-sm tracking-widest text-gold mb-4">FULL TRANSPARENCY REPORT</h3>
            {report ? (
              <div className="bg-card border border-border rounded-sm p-4 mb-4 max-h-96 overflow-y-auto">
                <pre className="text-muted-foreground text-sm whitespace-pre-wrap font-mono">{report}</pre>
              </div>
            ) : (
              <button onClick={handleGenerateReport} disabled={generatingReport} className="btn-primary w-full">
                {generatingReport ? 'GENERATING...' : 'GENERATE FULL REPORT — FREE'}
              </button>
            )}
            {report && (
              <button onClick={() => {
                const blob = new Blob([report], { type: 'text/plain' })
                const url = URL.createObjectURL(blob)
                const a = document.createElement('a')
                a.href = url
                a.download = `${selectedDrug.brandName}-transparency-report.txt`
                a.click()
              }} className="btn-secondary w-full mt-4">
                <Download className="w-4 h-4 mr-2" />
                DOWNLOAD REPORT
              </button>
            )}
          </div>
        </div>
      )}

      {/* Disclaimer */}
      <div className="mt-8 p-4 bg-card/50 border border-border rounded-sm">
        <p className="text-muted-foreground text-xs">
          <strong className="text-gold">DISCLAIMER:</strong> This report was generated by Apex Global Shield using publicly available data from pbs.gov.au, tga.gov.au, and legislation.gov.au. It may contain errors, inaccuracies, or outdated information. This is an information and research tool, NOT medical or pharmaceutical advice. Verify all information independently and consult a qualified healthcare professional before making medication decisions.
        </p>
      </div>
    </div>
  )
}

export default PharmaSearch
